version: "3"

services:

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    command: /pot/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - 9083:9083

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
